const soil = [
  { id: 1, condition: 'trocken' },
  { id: 2, condition: 'nass' },
  { id: 3, condition: 'komprimierter Boden' },
  { id: 4, condition: 'natürlicher/unkultivierter Boden' },
  { id: 5, condition: 'stickstoffarm' },
  { id: 6, condition: 'stickstoffreich' },
  { id: 7, condition: 'kaliumarm' },
  { id: 8, condition: 'kaliumreich' },
  { id: 9, condition: 'phosphorarm' },
  { id: 10, condition: 'phosphorreich' },
  { id: 11, condition: 'sandig' },
  { id: 12, condition: 'lehmig' },
  { id: 13, condition: 'tiefgreifende Mineralschicht' },
  { id: 14, condition: 'sauer' },
  { id: 15, condition: 'basisch' },
  { id: 16, condition: 'mager' },
  { id: 17, condition: 'nährstoffreich' },
  { id: 18, condition: 'salzig' },
];

const plants = [
  { name: 'Zurückgebogener Amaranth',
    latin: 'Amaranthus retroflexus',
    soil: [1, 3],
    img: 'AmaranthusRetroflexus.jpg',
    imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Amaranthus_retroflexus_full1.jpg',
    url: 'https://de.wikipedia.org/wiki/Zur%C3%BCckgebogener_Amarant',
    desc: 'Der Zurückgebogene Amarant (Amaranthus retroflexus), auch Zurückgekrümmter Fuchsschwanz oder Rauhaariger Amarant genannt, ist eine Pflanzenart innerhalb der Familie der Fuchsschwanzgewächse (Amaranthaceae). Er ist in Mitteleuropa ein häufiges, wärmeliebendes „Unkraut“ in Mais- und Zuckerrübenfeldern, in Haus- und Gemüsegärten sowie in Weinbergen.', },
  { name: 'Gemeiner Odermenning',
    latin: 'Agrimonia eupatoria',
    soil: [1],
    img: 'AgrimoniaEupatoria.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Gemeiner_Odermennig#/media/File:Agrimonia_eupatoria_04.jpg',
    url: 'https://de.wikipedia.org/wiki/Gemeiner_Odermennig',
    desc: 'Der Gewöhnliche Odermennig (Agrimonia eupatoria), auch Gemeiner Odermennig, Ackerkraut oder Kleiner Odermennig genannt, ist eine Pflanzenart in der Unterfamilie der Rosoideae innerhalb der Familie der Rosengewächse (Rosaceae). Sie ist in Eurasien weitverbreitet.', },
  { name: 'Acker-Gauchheil',
    latin: 'Anagallis arvensis',
    soil: [15],
    img: 'AnagallisArvensis.jpg',
    imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/1/15/AnagallisArvensis.jpg',
    url: 'https://de.wikipedia.org/wiki/Acker-Gauchheil',
    desc: 'Der Acker-Gauchheil (Anagallis arvensis), auch Roter Gauchheil, Nebelpflanze, Weinbergsstern oder Wetterkraut genannt, ist eine Pflanzenart aus der Gattung Gauchheil (Anagallis) in der Unterfamilie der Myrsinengewächse (Myrsinaoideae) innerhalb der Familie der Primelgewächse (Primulaceae). Er gilt im Ackerbau als Unkraut, weil er schwach giftig in all seinen Teilen ist, vor allem in der Wurzel.', },
  { name: 'Salz-Aster',
    latin: 'Aster tripolium',
    soil: [18],
    img: 'AsterTripolium.jpg',
    imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Strandasters.jpg',
    url: 'https://de.wikipedia.org/wiki/Strand-Aster',
    desc: 'Die Strand-Aster (Tripolium pannonicum, Syn.: Aster tripolium L.), auch Salz-Aster und Pannonien-Salzaster genannt, ist eine Pflanzenart in der Familie der Korbblütler (Asteraceae). Sie gehört zu den sehr auffälligen Pflanzenarten auf Salzböden.', },
  { name: 'Kanadisches Berufskraut',
    latin: 'Erigeron canadensis',
    soil: [2],
    img: 'ErigeronCanadensis.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Kanadisches_Berufkraut#/media/File:Conyza_canadense_002.JPG',
    url: 'https://de.wikipedia.org/wiki/Kanadisches_Berufkraut',
    desc: 'Das Kanadische Berufkraut (Conyza canadensis), auch Katzenschweif und Weiße Dürrwurz genannt, ist eine Pflanzenart aus der Familie der Korbblütler (Asteraceae). Es wird auch oft unter dem wissenschaftlichen Namen Erigeron canadensis der Gattung Erigeron geführt.', },
  { name: 'Gewöhnliches Greiskraut',
    latin: 'Senecio vulgaris',
    soil: [3, 17],
    img: 'SenecioVulgaris.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Gew%C3%B6hnliches_Greiskraut#/media/File:20150418Senecio_vulgaris6.jpg',
    url: 'https://de.wikipedia.org/wiki/Gew%C3%B6hnliches_Greiskraut',
    desc: 'Das Gewöhnliche Greiskraut (Senecio vulgaris), auch Gemeines Greiskraut oder Gemeines Kreuzkraut genannt, ist eine der häufigsten Arten aus der Gattung der Greiskräuter (Senecio) innerhalb der Familie der Korbblütler (Asteraceae).', },
  { name: 'Adlerfarn',
    latin: 'Pteridium aquilinum',
    soil: [7, 9, 14],
    img: 'PteridiumAquilinum.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Adlerfarn#/media/File:Pteridium_aquilinum_(habitus).jpg',
    url: 'https://de.wikipedia.org/wiki/Adlerfarn',
    desc: 'Der Adlerfarn (Pteridium aquilinum) ist ein weltweit verbreiteter, auffälliger Farn. Die Farne sind eine Gruppe von Gefäßsporenpflanzen, die die Schwestergruppe der Samenpflanzen bilden.',
    photographer: 'Hans Hillewaert', },
  { name: 'Schwarzes Bilsenkraut',
    latin: 'Hyoscyamus niger',
    soil: [15],
    img: 'HyoscyamusNiger.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Schwarzes_Bilsenkraut#/media/File:Hyoscyamus_niger_0003.JPG',
    url: 'https://de.wikipedia.org/wiki/Schwarzes_Bilsenkraut',
    desc: 'Das Schwarze Bilsenkraut (Hyoscyamus niger) ist eine Pflanze aus der Gattung der Bilsenkräuter aus der Familie der Nachtschattengewächse (Solanaceae). Schwarzes Bilsenkraut wächst in Schuttunkrautgesellschaften, an Wegrändern, Mauern usw. Es bevorzugt frische, nährstoff- und stickstoffreiche Sand- oder Lehmböden.',
    photographer: 'H. Zell', },
  { name: 'Gemeiner Beifuß',
    latin: 'Artemisia vulgaris',
    soil: [4],
    img: 'ArtemisiaVulgaris.jpg',
    imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/ArtemisiaVulgaris.jpg',
    url: 'https://de.wikipedia.org/wiki/Beifu%C3%9F',
    desc: 'Der Beifuß oder Gemeine Beifuß (Artemisia vulgaris), auch Gewürzbeifuß oder Gewöhnlicher Beifuß genannt, ist eine Pflanzenart aus der Gattung Artemisia in der Familie der Korbblütler (Asteraceae, veraltet Compositae). Auf nährstoffreichen Böden, vor allem Ruderalfluren kommt der Beifuß wild vor.',
    photographer: 'Christian Fischer', },
  { name: 'Gemeine Wegwarte',
    latin: 'Cichorium intybus',
    soil: [3, 12, 17],
    img: 'CichoriumIntybus.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Gemeine_Wegwarte#/media/File:Cichorium_Intybus.jpg',
    url: 'https://de.wikipedia.org/wiki/Gemeine_Wegwarte',
    desc: 'Die Gemeine oder Gewöhnliche Wegwarte (Cichorium intybus), auch Zichorie (von lateinisch cichorea) genannt, ist eine Pflanzenart aus der Familie der Korbblütler (Asteraceae). Sie wächst in Mitteleuropa häufig an Wegrändern. Kulturformen sind Chicorée, Zuckerhut (Fleischkraut), Radicchio, Schnittzichorie und die Wurzelzichorie. Sie kommt vorwiegend auf frischen bis eher trockenen, nährstoffreichen Böden vor und erträgt auch einen gewissen Salzgehalt.',
    photographer: 'Christian Fischer', },
  { name: 'Gewöhnliche Vogelmiere',
    latin: 'Stellaria media',
    soil: [3, 17],
    img: 'StellariaMedia.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Gew%C3%B6hnliche_Vogelmiere#/media/File:Chickweed_(aka).jpg',
    url: 'https://de.wikipedia.org/wiki/Gew%C3%B6hnliche_Vogelmiere',
    desc: 'Die Gewöhnliche Vogelmiere (Stellaria media), auch Vogel-Sternmiere, Hühnerdarm, Hühnerscherbe oder Hustdarm genannt, ist eine Pflanzenart der Familie der Nelkengewächse (Caryophyllaceae). Das weit verbreitete „Unkraut“ kann als Wildgemüse und Heilpflanze verwendet werden. Sie bevorzugt feuchte, nährstoffreiche Böden, die auch im Schatten liegen können. Verbreitet ist sie von der Ebene bis ins Gebirge. Nach Ellenberg ist sie ein Schwachsäure- bis Schwachbasenzeiger, ein ausgesprochener Stickstoffzeiger und eine Ordnungscharakterart nährstoffreicher Acker- und Garten-Beikrautfluren (Polygono-Chenopodietalia)',
    photographer: 'André Karwath', },
  { name: 'Huflattich',
    latin: 'Tussilago farfara',
    soil: [2, 12, 14],
    img: 'TussilagoFarfara.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Huflattich#/media/File:Coltsfoot.jpg',
    url: 'https://de.wikipedia.org/wiki/Huflattich',
    desc: 'Der Huflattich (Tussilago farfara) ist die einzige Pflanzenart der Gattung Tussilago aus der Familie der Korbblütler (Asteraceae). Er gehört zu den ersten Frühjahrsblumen, deren Blüten vor der Entwicklung der Laubblätter erscheinen. Der Huflattich war in Deutschland die Heilpflanze des Jahres 1994. Er ist auch bekannt unter den Namen Breit-, Brust- oder Eselslattich, Latten, Lette, Ackerlatsche, Kuhfladen, Esels- oder Rosshuf, Eselstappe, Fohlenfuß und Hufblatt. Er besiedelt trocken-warme Standorte auf durchlässigen Böden. Daher tritt der Huflattich oft auf Dämmen, in Steinbrüchen und an unbefestigten Wegen auf.',
    photographer: 'Andreas Trepte', },
  { name: 'Wilde Möhre',
    latin: 'Daucus carota',
    soil: [4, 11, 15, 16],
    img: 'DaucusCarota.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Wilde_M%C3%B6hre#/media/File:Daucus_carotaA.jpg',
    url: 'https://de.wikipedia.org/wiki/Wilde_M%C3%B6hre',
    desc: 'Die in Mitteleuropa heimische Wilde Möhre (Daucus carota subsp. carota) ist ein Elternteil der Gartenmöhre oder Karotte. Sie gehört zur Familie der Doldenblütler (Apiaceae). Im Gegensatz zur Gartenmöhre ist die Speicherwurzel der Wilden Möhre bleich. Die Wilde Möhre besitzt ihr Hauptvorkommen in nährstoffreichen Stauden- und ausdauernden Unkrautfluren, halbruderalen Queckenrasen trockenwarmer Standorte. Frischwiesen und -weiden zählen ebenso zu den oft besiedelten Standorten. Sie gedeiht hauptsächlich im Offenland, aber auch im Wald. Oft findet man sie auch auf Ruderalflächen.',
    photographer: 'Christian Fischer', },
  { name: 'Gewöhnliche Goldrute',
    latin: 'Solidago virgaurea',
    soil: [2, 11],
    img: 'SolidagoVirgaurea.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Gew%C3%B6hnliche_Goldrute#/media/File:Solidago_virgaurea09.jpg',
    url: 'https://de.wikipedia.org/wiki/Gew%C3%B6hnliche_Goldrute',
    desc: 'Die Gewöhnliche Goldrute (Solidago virgaurea), auch Gemeine Goldrute oder Echte Goldrute genannt, ist eine Pflanzenart aus der Gattung der Goldruten (Solidago) innerhalb der Familie der Korbblütler (Asteraceae).',
    photographer: 'Stéphane TASSON', },
  { name: 'Weißer Gänsefuß',
    latin: 'Chenopodium album',
    soil: [3, 17],
    img: 'ChenopodiumAlbum.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Wei%C3%9Fer_G%C3%A4nsefu%C3%9F#/media/File:Melganzenvoet_bloeiwijze_Chenopodium_album.jpg',
    url: 'https://de.wikipedia.org/wiki/Wei%C3%9Fer_G%C3%A4nsefu%C3%9F',
    desc: 'Der Weiße Gänsefuß (Chenopodium album), auch Weiß-Gänsefuß genannt,[1] ist eine Pflanzenart aus der Gattung Gänsefuß (Chenopodium) in der Familie der Fuchsschwanzgewächse (Amaranthaceae). In Mitteleuropa meist als landwirtschaftliches Unkraut betrachtet, dient er in anderen Regionen als Gemüse, Pseudogetreide oder Futterpflanze. Man findet ihn in Mitteleuropa verbreitet in Ruderalvegetation und Unkrautfluren, vor allem als Erstbesiedler auf Schuttplätzen, an Wegen, in Äckern und Gärten, auch an Ufern und in Schlägen. Er gedeiht auf allen ausreichend nährstoffreichen Böden.',
    photographer: 'Rasbak', },
  { name: 'Acker-Hundskamille',
    latin: 'Anthemis arvensis',
    soil: [2, 7, 13, 15],
    img: 'AnthemisArvensis.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Acker-Hundskamille#/media/File:Anthemis_arvensis_(subsp._arvensis)_sl5.jpg',
    url: 'https://de.wikipedia.org/wiki/Acker-Hundskamille',
    desc: 'Die Acker-Hundskamille (Anthemis arvensis) ist eine Pflanzenart innerhalb der Familie der Korbblütler (Asteraceae). Die Acker-Hundskamille ist ein Ackerwildkraut, ein Archäophyt, ein Kulturbegleiter und ein Versauerungszeiger. Als Standorte werden Äcker, Brachflächen und Wegränder, besonders auf kalkfreien, sauren Böden bevorzugt. Diese Pflanzenart ist in ganz Europa häufig.',
    photographer: 'Stefan.lefnaer', },
  { name: 'Gewöhnlicher Hirtentäschen',
    latin: 'Capsella bursa pastoris',
    soil: [11, 18],
    img: 'CapsellaBursaPastoris.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Gew%C3%B6hnliches_Hirtent%C3%A4schel#/media/File:Hirtent%C3%A4schel_in_Trebus_2007.JPG',
    url: 'https://de.wikipedia.org/wiki/Gew%C3%B6hnliches_Hirtent%C3%A4schel',
    desc: 'Das Gewöhnliche Hirtentäschel (Capsella bursa-pastoris), auch Hirtentäschelkraut genannt, ist eine Pflanzenart in der Familie der Kreuzblütengewächse (Brassicaceae). Der wissenschaftliche Name Capsella bursa-pastoris kommt von lat. capsa = Kapsel, bursa = Tasche und pastor = Hirt, da die Schötchen der Pflanze wie die Taschen früherer Hirten geformt sind. Diese Art kommt in ganz Europa vor und ist in Mitteleuropa sehr häufig. Als Standorte werden Ruderalstellen, Äcker und Gärten bevorzugt. Die Pflanze ist stickstoff- und lichtliebend und gedeiht auf nährstoffreichen Böden. Das Hirtentäschelkraut kommt bis in die subalpine Höhenstufe vor.',
    photographer: 'Conrad Nutschan', },
  { name: 'Gewöhnlicher Erdrauch',
    latin: 'Fumaria officinalis',
    soil: [8],
    img: 'FumariaOfficinalis.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Gew%C3%B6hnlicher_Erdrauch#/media/File:Fumaria_officinalis_003.JPG',
    url: 'https://de.wikipedia.org/wiki/Gew%C3%B6hnlicher_Erdrauch',
    desc: 'Der Gewöhnliche Erdrauch (Fumaria officinalis), auch Gemeiner Erdrauch genannt, ist die in Mitteleuropa häufigste Pflanzenart der Gattung Erdrauch (Fumaria). Diese Art gilt als Nährstoffanzeiger. Sie wächst auf bearbeitetem Boden wie in Gärten, auf Äckern oder Weinbergen oder an Ruderalstellen, wo sie überall häufig ist. Dabei tritt sie in kleinen Gruppen oder als Einzelexemplar auf. Sie gedeiht auf frischen, basenreichen, milden bis mäßig sauren, humosen lockeren Lehmböden.',
    photographer: 'H. Zell', },
  { name: 'Strahlenlose Kamille',
    latin: 'Matricaria matricarioides',
    soil: [13],
    img: 'MatricariaMatricarioides.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Strahlenlose_Kamille#/media/File:Plant_on_puddle.jpg',
    url: 'https://de.wikipedia.org/wiki/Strahlenlose_Kamille',
    desc: 'Die Strahlenlose Kamille (Matricaria discoidea), auch Strahllose Kamille genannt, ist eine Pflanzenart aus der Gattung der Kamillen (Matricaria); sie gehört zur Unterfamilie der Asteroideae innerhalb der Familie der Korbblütler (Asteraceae). Sie tritt in gemäßigten Zonen weltweit als Neophyt auf. Sie kommt in Trittrasen, vor allem in Siedlungsnähe vor; sie wächst dort oft in größeren Gruppen. Sie bevorzugt offenen, nährstoffreichen, dichten Lehm- und Tonboden. Nach Ellenberg ist sie eine Lichtpflanze, ein Mäßigwärmezeiger, ein Frischezeiger, ein Schwachsäure- bis Schwachbasezeiger, ein ausgesprochener Stickstoffzeiger und eine Verbandscharakterart der Vogelknöterich-Trittrasen-Gesellschaften (Polygonion avicularis).',
    photographer: 'Tiia Monto', },
  { name: 'Acker-Rettich',
    latin: 'Raphanus raphanistrum',
    soil: [4, 14, 16],
    img: 'RaphanusRaphanistrum.jpg',
    imgSrc: 'https://en.wikipedia.org/wiki/Raphanus_raphanistrum#/media/File:Wild_Radish.jpg',
    url: 'https://de.wikipedia.org/wiki/Acker-Rettich',
    desc: 'Acker-Rettich (Raphanus raphanistrum), auch Hederich oder Wilder Rettich genannt, ist eine Pflanzenart aus der Gattung Rettiche (Raphanus) innerhalb der Familie der Kreuzblütengewächse (Brassicaceae). Trotz seines Namens bildet er keine verdickte Wurzel und ist kein Vorfahre des Garten-Rettichs (Raphanus sativus), sondern lediglich mit ihm verwandt. Der Acker-Hederich kommt häufig in Unkrautfluren der Äcker und besonders der Getreidefelder, auch an Schuttplätzen vor. Er bevorzugt kalkarme Böden und zeigt Bodenversauerung an. Er wird auch als Gründüngung gesät.',
    photographer: 'Joanna Voulgaraki', },
  { name: 'Hasen-Klee',
    latin: 'Trifolium arvense',
    soil: [1, 8, 14],
    img: 'TrifoliumArvense.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Hasen-Klee#/media/File:20140728Trifolium_arvense2.jpg',
    url: 'https://de.wikipedia.org/wiki/Hasen-Klee',
    desc: 'Der Hasen-Klee (Trifolium arvense) ist eine Pflanzenart aus der Gattung Klee (Trifolium) innerhalb der Familie der Hülsenfrüchtler (Fabaceae). Der Hasen-Klee besiedelt in Mitteleuropa ziemlich häufig lückige Magerrasen, Sandfelder und Felsköpfe, Wegränder, Sandwege und Dämme, in Brachland und Äcker (beispielsweise Hackfruchtäcker).[4] Der Hasen-Klee gedeiht am besten auf lockeren feinerdearmen, ziemlich trockenen, kalkarmen und daher etwas bis mäßig sauren, rohen, sandigen oder steinig-grusigen Böden. Nach Ellenberg ist er eine Lichtpflanze, ein Trockniszeiger, stickstoffärmste Standorte anzeigend und in Mitteleuropa eine Klassencharakterart lockerer Sand- und Felsrasen (Sedo-Scleranthetea).',
    photographer: 'AnRo0002', },
  { name: 'Weiß-Klee',
    latin: 'Trifolium repens',
    soil: [1, 4],
    img: 'TrifoliumRepens.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Wei%C3%9Fklee#/media/File:TrifoliumRepensFlowers.jpg',
    url: 'https://de.wikipedia.org/wiki/Wei%C3%9Fklee',
    desc: 'Der Weißklee (Trifolium repens), auch Kriechklee genannt, ist eine Pflanzenart, die zur Unterfamilie der Schmetterlingsblütler (Faboideae) innerhalb der Familie der Hülsenfrüchtler (Fabaceae oder Leguminosae) gehört. Der Weißklee besiedelt hauptsächlich Wiesen und Weideland. Da er sehr trittresistent ist, ist er oft auch an Wegrändern und in Sportanlagen zu finden. Er bevorzugt nährstoffreiche, leicht kalkhaltige, lehmige, feuchte Böden und wächst auch in Sandboden, welcher noch Hafer trägt.',
    photographer: 'Fanghong', },
  { name: 'Wiesen-Klee',
    latin: 'Trifolium pratense',
    soil: [8],
    img: 'TrifoliumPratense.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Wiesenklee#/media/File:Trifolium_pratense_-_Keila2.jpg',
    url: 'https://de.wikipedia.org/wiki/Wiesenklee',
    desc: 'Der Wiesenklee (Trifolium pratense), auch Rotklee genannt,[1] ist eine Pflanzenart aus der Gattung Klee (Trifolium) in der Unterfamilie der Schmetterlingsblütler (Faboideae) innerhalb der Familie der Hülsenfrüchtler (Fabaceae oder Leguminosae). Man findet den Wiesenklee in Fettwiesen, auf Feldern und in lichten Wäldern, auch als Kulturpflanze wird er angebaut. Er bevorzugt frische, nährstoffreiche, tiefgründige Ton- und Lehmböden und ist kalk- und sulfatliebend.',
    photographer: 'Ivar Leidus', },
  { name: 'Einjähriger Knäuel',
    latin: 'Scleranthus annuus',
    soil: [14],
    img: 'ScleranthusAnnuus.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Einj%C3%A4hriger_Kn%C3%A4uel#/media/File:Scleranthus_annuus_eF.jpg',
    url: 'https://de.wikipedia.org/wiki/Einj%C3%A4hriger_Kn%C3%A4uel',
    desc: 'Der Einjährige Knäuel (Scleranthus annuus), auch Einjahrs-Knäuelkraut genannt, ist ein Angehöriger der Nelkengewächse (Caryophyllaceae). Er blüht von Mai bis Oktober. Der Einjährige Knäuel wächst in Ackerunkrautfluren, seltener auch an Wegen oder Schuttplätzen. Er bevorzugt mäßig trockenen bis frischen, mehr oder weniger nährstoffreichen, kalkarmen, mäßig sauren Sandboden oder sandigen Lehmboden. Es ist ein bis zu 20 cm tief wurzelnder Versauerungszeiger.',
    photographer: 'Fornax', },
  { name: 'Kornblume',
    latin: 'Centaurea cyanus',
    soil: [11],
    img: 'CentaureaCyanus.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Kornblume#/media/File:Kornblume02.JPG',
    url: 'https://de.wikipedia.org/wiki/Kornblume',
    desc: 'Die Kornblume (Cyanus segetum Hill, Syn.: Centaurea cyanus L.), auch Zyane genannt, ist eine Pflanzenart aus der Gattung Cyanus innerhalb der Familie der Korbblütler (Asteraceae). Seitdem der Mensch Ackerbau betreibt, ist die Kornblume eine ständige Begleiterin von Getreidefeldern. Doch auch an Schuttplätzen und recht trockenen Standorten ist die Kornblume stellenweise zu finden. Lange Zeit war sie durch Überdüngung der Felder selten geworden. Sie ist ein Bioindikator, der anzeigt, wie stark die Felder in vergangenen Jahren gedüngt wurden. Heutzutage ist sie wieder häufiger anzutreffen.',
    photographer: 'böhringer friedrich', },
  { name: 'Kriech-Quecke',
    latin: 'Elymus repens',
    soil: [13],
    img: 'ElymusRepens.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Kriech-Quecke#/media/File:Kweek_Elytrigia_repens.jpg',
    url: 'https://de.wikipedia.org/wiki/Kriech-Quecke',
    desc: 'Die Kriech-Quecke (Elymus repens), auch Gemeine Quecke, Gewöhnliche Quecke oder einfach Quecke genannt, ist eine Pflanzenart aus der Gattung Quecken (Elymus) innerhalb der Familie der Süßgräser (Poaceae). Der Trivialname Quecke ist aus queck, quick = „zählebig“ entstanden. Dieses Gras ist nahezu weltweit verbreitet und stellt eine Pionierpflanze auf fast allen Böden dar. Die Kriech-Quecke kommt auf Ackerflächen, nährstoffreichen Wiesen („Jauchewiesen“), überweideten Weiden, an Wegen, in Ufersäumen und in Unkrautgesellschaften vor, etwa an Dämmen oder Schuttplätzen. Es handelt sich um eine Halblichtpflanze, die vor allem an stickstoffreichen Standorten wächst. Sie gedeiht auf frischen bis mäßig trockenen, nährstoff- und basenreichen, humosen oder rohen, oft dichten Lehm- oder Tonböden.',
    photographer: 'Rasbak', },
  { name: 'Lupinen',
    latin: 'Lupinus sp.',
    soil: [5],
    img: 'Lupinus.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Lupinen#/media/File:Lupinen.jpg',
    url: 'https://de.wikipedia.org/wiki/Lupinen',
    desc: 'Die Lupinen (Lupinus; von althochdeutsch luvina, zu lateinisch lupus, deutsch ‚Wolf‘), selten auch Wolfsbohne oder Feigbohne genannt, sind eine Pflanzengattung in der Unterfamilie der Schmetterlingsblütler (Faboideae) innerhalb der Familie der Hülsenfrüchtler (Fabaceae oder Leguminosae). Zur gleichen Familie gehören beispielsweise Erbse, Kichererbse und Erdnuss. Die Samen insbesondere wilder und Gartenlupinen enthalten Lupinin, einen giftigen Bitterstoff, der den Tod durch Atemlähmung verursachen kann. Bestimmte Zuchtformen hingegen sind ungiftig und nicht bitter. Lupinen reichern den Boden mit bis zu 100 kg Stickstoff pro Hektar an, was in der Landwirtschaft zur Gründüngung erwünscht sein kann. Die kräftigen Wurzeln können auch verdichteten Boden durchdringen und so die Durchwurzelbarkeit des Bodens für Folgekulturen verbessern. Die Symbionten binden den Stickstoff aus der Luft und lösen zudem einen Teil des Phosphats im Boden.',
    photographer: 'Hedi Schäfer', },
  { name: 'Wermuth',
    latin: 'Artemisia absinthium',
    soil: [18],
    img: 'ArtemisiaAbsinthium.jpg',
    imgSrc: 'https://de.wikipedia.org/wiki/Wermutkraut#/media/File:Artemisia_absinthium_0002.JPG',
    url: 'https://de.wikipedia.org/wiki/Wermutkraut',
    desc: '(Gemeiner) Wermut, Echt-Wermut[1] oder Wermutkraut (Artemisia absinthium L.), auch Bitterer Beifuß oder Alsem, ist eine Pflanzenart in der Gattung Artemisia aus der Familie der Korbblütler (Asteraceae). Wermut wird seit der Antike als Heilpflanze eingesetzt. Er wächst bevorzugt auf trockenen oder auf sandig-tonigen Böden in der Nähe von Wasserläufen in Höhen bis zu 3500 Meter.',
    photographer: 'H. Zell', },
  { name: 'Melde sp.',
    latin: 'Atriplex sp.',
    soil: [17],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Löwenzahn',
    latin: 'Taraxacum officinale',
    soil: [3, 12, 14],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Kleine Brennnessel',
    latin: 'Urtica urens',
    soil: [2, 3, 14],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Magerwiesen Margerite',
    latin: 'Chrysanthemum leucanthemum',
    soil: [2, 4],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Acker-Schachtelhalm',
    latin: 'Euisetum arvense',
    soil: [2, 11],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Acker-Hellerkraut',
    latin: 'Thlaspi arvense',
    soil: [13, 15],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Floh-Knöterich',
    latin: 'Polygonum persicaria',
    soil: [2, 14],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Vogelknöterich',
    latin: 'Polygonum aviculare',
    soil: [3, 14],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Silber-Fingerkraut',
    latin: 'Potentilla argentea',
    soil: [1, 14],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Scharfer Hahnenfuß',
    latin: 'Ranunculus acris',
    soil: [2, 3, 12],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Kriechender Hahnenfuß',
    latin: 'Ranunculus repens',
    soil: [2, 12],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Raps',
    latin: 'Brassica napus',
    soil: [5],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Kleiner Sauerampfer',
    latin: 'Rumex acetosella',
    soil: [11, 14],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Gemeine Schafgarbe',
    latin: 'Achillea millefolium',
    soil: [7],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Kompass-Lattich',
    latin: 'Lactuca serriola',
    soil: [3],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Gefleckter Schierling',
    latin: 'Conium maculatum',
    soil: [2],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Stumpfblättriger Ampfer',
    latin: 'Rumex obtusifolius',
    soil: [2, 12],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Hopfenklee',
    latin: 'Medicago lupulina',
    soil: [5, 15],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Acker-Winde',
    latin: 'Convolvulus arvensis',
    soil: [11, 13],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Echte Zaunwinde',
    latin: 'Convovulus sepium',
    soil: [2],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Acker-Spark',
    latin: 'Spergula arvensis',
    soil: [11, 14],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Acker-Gänsedistel',
    latin: 'Sonchus arvensis',
    soil: [12, 14],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Acker-Kratzdistel',
    latin: 'Cirsium arvensis',
    soil: [12],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Gänseblümchen',
    latin: 'Bellis perennis',
    soil: [12, 14],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
  { name: 'Echtes Leinkraut',
    latin: 'Linaria vulgaris',
    soil: [12],
    img: '',
    imgSrc: '',
    url: '',
    desc: '',
    photographer: '', },
];

function filterPlants(soilCondition) {
  let conditionId = soil.filter(x => x.condition === soilCondition)[0].id;
  let filteredPlants = plants.filter(x => x.soil.includes(conditionId))
                             .map(plant => plant.latin);

  document.querySelectorAll('.plant')
        .forEach(plant => {
          filteredPlants.includes(plant.id) ? plant.classList.remove('hide') :
                                              plant.classList.add('hide');
        });
  window.scrollTo(0, 0);
}

function showPlants() {
  const plantsList = document.getElementById('plants-list');

  /* add one card per entry in plants object */
  for (let i = 0; i < plants.length; i++) {
    const card = document.createElement('div');
    card.setAttribute('class', 'plant');
    card.setAttribute('id', `${plants[i].latin}`);
    card.innerHTML = `
            <div class="card">
              <a href="${plants[i].url}" target="_blank"><img class="card-img-top"
                   src="img/500x500/${plants[i].img}"
                   alt="${plants[i].name}"></a>
              <div class="card-body" id="${plants[i].name}">
                <h5 class="card-title">${plants[i].name}</h5>
                <h6><em>${plants[i].latin}</em></h6>
                <p class="card-text">${plants[i].desc}</p>
              </div>
            </div>`;
    plantsList.appendChild(card);

    /* add respective soil conditions accordingly to plant info in
       plants object soil condition array */
    const cardBody = document.getElementById(plants[i].name);
    for (let j = 0; j < plants[i].soil.length; j++) {
      const span = document.createElement('span');
      span.setAttribute('class', 'soil-info');
      span.addEventListener('click', function () {
        filterPlants(this.innerText);
      });

      // the index is one less than reference in plants object
      span.innerHTML = `${soil[plants[i].soil[j] - 1].condition}`;
      cardBody.appendChild(span);
    }
  }
}

showPlants();
